# Generated by Django 5.1.1 on 2024-10-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="deviceId",
        ),
        migrations.AddField(
            model_name="customuser",
            name="conversationData",
            field=models.JSONField(default=dict),
        ),
    ]
